version: '3'
services:
  ollama:
    image: ollama/ollama #ollama_tiny_dolphin_container_image
    restart: on-failure
    container_name: ollama_tiny_dolphin_container
    ports:
      - "11435:11435"
    volumes:
      - 'ollama_tiny_dolphin_volume:/usr/share/ollama/tiny_dolphin/data'

volumes:
  ollama_tiny_dolphin_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: K:\projet\AI\src\docker\ollama\volumes\ollama\tiny_dolphin
