#!/usr/bin/env php
<?php

use GillesPinchart\Ai\APP\console\console;
use GillesPinchart\Ai\APP\server\server;

require_once(__DIR__ . '/base_app.php');
define('AI_START', microtime(true));

// INIT
$env     = "" ;
$console = new console($argv);
$server  = new server();

// RUN COMMAND
switch ($console->action()){

    case 'cmd':
        try {
            $console->command(function () use($console){
                switch ($console->param()){
                    case 'test':
                        dd("TEST");
                        break;
                    default:
                        dd("Codes ici ... ou dans le switch case");
                        break;
                }
            });
        } catch (Exception $e) {
            dd($e);
        }
        break;

    case 'serve':
        $base_dir = __DIR__;
        $server->web_server($base_dir);
        break;
}