    version: '3'
    services:
      ollama:
        image: ollama/ollama #ollama_tiny_dolphin_container_image
        container_name: ollama_mistral_container
        ports:
          - "11434:11434"
        volumes:
          - 'ollama_mistral_volume:/usr/share/ollama/mistral/data'
    
    volumes:
      ollama_mistral_volume:
        driver: local
        driver_opts:
          type: none
          o: bind
          device: H:\AI\src\docker\ollama\volumes\ollama\mistral
