version: '3'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama_mistral_container
    ports:
      - "11434:11434"
    volumes:
      - 'ollama_mistral_volume:/usr/share/ollama/mistral/data'

volumes:
  ollama_mistral_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: K:\projet\AI\src\docker\ollama\volumes\ollama\mistral