    version: '3'
    services:
      ollama:
        image: ollama/ollama #ollama_tiny_dolphin_container_image
        container_name: ollama_mistral_container
        ports:
          - "ollama_mistral_volume"
        volumes:
          - '/usr/share/ollama/mistral/data:K:\projet\AI\src\docker\ollama\volumes\ollama\mistral'
    
    volumes:
      /usr/share/ollama/mistral/data:
        driver: local
        driver_opts:
          type: none
          o: bind
          device: 3
